name: Renovar livros

on:
  schedule:
    - cron: '0 12 * * 1'

jobs:
  run_task:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Rodar o script para renovar livros
        run: |
          python3 renovarBiblioteca.py
