name: Renovar livros

on:
  schedule:
    - cron: '0 12 * * 1' 
  workflow_dispatch: 

jobs:
  run_task:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Configurar o ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install Playwright
          playwright install

      - name: Rodar o script para renovar livros
        run: |
          python3 renovarBiblioteca.py
